### PR TITLE
#39 Change button to light green during ncorr

### PR DESCRIPTION
**Pull request by markhalonen**
relinc/SurePulseDataProcessor#39

My computer switches too fast so I can't really see if this actually worked. Maybe I need larger images? I tested with 1200 images and it still went too fast.

I did what testing I could but this is not fully tested

### CODE REVIEW

**Comment by bhalonen** [comment]
hilarious. Windows might be slower.

**Comment by markhalonen** [comment]
No, I think my images are just too small. It looks like the resize process is what they are waiting for and nothing is happening.

**Comment by markhalonen** [comment]
I am running on Windows. I don't know if ncorr runs on Mac

**Comment by bhalonen** [comment]
Forgot. Luke's computer did have a half beat hesitation before the ncorr computing screen loaded.

**Comment by bhalonen** [comment]
It took about 3 seconds to transition to the correct screen.

**Comment by markhalonen** [comment]
I tried jpeg images from Kirana and I didn't notice any lag. Maybe GoPro images?

**Pull request merged**
